name: Run Python Scripts via GitHub App

on:
  issues:
    types: [opened]

jobs:
  trigger-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Send Webhook to Trigger Script
      run: |
        curl -X POST "https://my-app-y984.onrender.com/webhook" \
        -H "Content-Type: application/json" \
        -H "X-GitHub-Event: issues" \
        -H "X-Hub-Signature-256: sha256=testsignature" \
        -d '{"issue": {"title": "${{ github.event.issue.title }}"}}'

