name: Run Python Scripts

on:
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - main
  issues: # Triggered when an issue is created

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Hello World
        run: python src/hello_world.py

      - name: Run Calculator
        run: |
          echo -e "1\n+\n2" | python src/calculator.py

      - name: Run Guess Number
        run: |
          echo -e "50\n25\n75\n100" | python src/guess_number.py

      - name: Run Monitor Directory
        run: python src/monitor_directory.py
