name: Run Python Scripts

on:
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - main
  issues: # Triggered when an issue is created

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Hello World
        env:
          USER_NAME: "GitHub Runner"
        run: python src/hello_world.py

      - name: Run Calculator
        env:
          NUM1: "10"
          OPERATION: "+"
          NUM2: "5"
        run: python src/calculator.py

      - name: Run Guess Number
        env:
          ATTEMPTS: "10"
        run: python src/guess_number.py

      - name: Run Monitor Directory
        env:
          TARGET_DIRECTORY: "./public"
          MONITOR_TIMEOUT: "10"
        run: python src/monitor_directory.py

